spring:
  profiles:
    active: local  # 기본 활성 프로필

  jackson:
    serialization:
      write-dates-as-timestamps: false

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger
    use-root-path: true
    doc-expansion: none
    groups-order: asc
    tags-sorter: alpha
    operations-sorter: alpha

watery:
  secret:
    key: ${WATERY_SECRET_KEY}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace