spring:
  profiles:
    active: local  # 기본 활성 프로필

  jackson:
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql: trace
    
jwt:
  secret: ${WATERY_SECRET_KEY}
  access-token:
    expiration-second: 3600  # 1 hour (60 * 60 seconds)
  refresh-token:
    expiration-second: 604800  # 7 days (60 * 60 * 24 * 7 seconds)

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger
    use-root-path: true
    doc-expansion: none
    groups-order: asc
    tags-sorter: alpha
    operations-sorter: alpha
